### ISSUE TITLE
memcache store incompatibility ? -- undefined method alive?

### ISSUE THREAD

**Issue by lapatate** [ikai/jruby-memcache-client#1]
<pre>
log/staging.log_2009-08-30T03-50-46:SEVERE: undefined method `alive?' for "0.0.0.0:11211":String
log/staging.log_2009-08-30T03-50-46-    from /Users/pat/Applications/jruby-1.3.1/lib/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/session/mem_cache_store.rb:19:in `any?'
log/staging.log_2009-08-30T03-50-46-    from /Users/pat/Applications/jruby-1.3.1/lib/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/session/mem_cache_store.rb:19:in `initialize'
log/staging.log_2009-08-30T03-50-46-    from /Users/pat/Applications/jruby-1.3.1/lib/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/middleware_stack.rb:72:in `build'
log/staging.log_2009-08-30T03-50-46-    from /Users/pat/Applications/jruby-1.3.1/lib/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/middleware_stack.rb:116:in `each'
log/staging.log_2009-08-30T03-50-46-    from /Users/pat/Applications/jruby-1.3.1/lib/ruby/gems/1.8/gems/actionpack-2.3.2/lib/action_controller/middleware_stack.rb:116:in `inject'
</pre>

Now i created another memcache store to overcome this issue, but ran into marshal data errors afterwards

<pre>
log/staging.log:ActionView::TemplateError (marshal data too short) on line #93 of app/views/layouts/v1_4.html.erb:
log/staging.log-90:           <% end %>
log/staging.log-91:         </div>
log/staging.log-92:         <div id="yield" class="span-17 last">
log/staging.log-93:           <% unless flash[:message].blank? %>
log/staging.log-94:             <div id = "flash-message"><%= flash[:message] %></div>
</pre>

Tried on a new, empty project with rails 2.3.2 and jruby 1.3.1, your ikai gem 1.5.1 and still a nogo
I had used the environment.rb implementation as suggested in your README:

<pre>
<code>
if RUBY_PLATFORM =~ /java/i
  # Based on instructions from http://www.mikeperham.com/2009/03/03/using-memcache-client-16x-in-rails-23/
  # Brain surgery to use our own version of memcache-client without
  # having to modify activesupport directly.
  # Unload any previous instance of the class
  if Object.const_defined? :MemCache
    Object.instance_eval { remove_const :MemCache }
  end
  # Pull in the exact version we want
  gem 'ikai-jruby-memcache-client', '1.5.1'

  # Ensure that the memcache-client path is at the front of the loadpath
  $LOAD_PATH.each do |path|
    if path =~ /ikai-jruby-memcache-client/
      $LOAD_PATH.delete(path)
      $LOAD_PATH.unshift(path)
    end
  end
  # If Ruby thinks it's already loaded memcache.rb, force
  # a reload otherwise just require.
  if $".find { |file| file =~ /\Amemcache.rb\Z/ }
    load 'memcache.rb'
  else
    require 'memcache'
  end
end

memcache_options = {
        :namespace => 'fortaleza:production_live:',
        }
memcached_servers = [ ENV['MEMCACHED_LOCATION'] || '0.0.0.0:11211']

# Constant used by libs
CACHE = MemCache.new memcached_servers, memcache_options if RUBY_PLATFORM =~ /java/
</code>
</pre>

**Comment by fredjean** [comment]
Rail's session store checks each of the servers registered with the memcache client to see whether any of them are valid. We are storing the servers as an array of strings, which do not have the alive? method.

You should still be able to use it as a Rails cache store.

I am looking into this right now since it is impeding our own efforts to upgrade to Rails 2.3.4

**Comment by fredjean** [comment]
The gem loads in a test Rails 2.3.4 app. Give it a try.
