### ISSUE TITLE
memcache java library is not compiled for 1.5 compatibility

### ISSUE THREAD

**Issue by bjones** [ikai/jruby-memcache-client#3]
Try using with java 1.5, you'll get a class version error.  Solution is to download the library source and compile it yourself.  Be aware it requires 1.5 or higher.  Copy the .jar over to where it belongs and things should work.  I'd recommend at least a warning that the compiled version included with this client only works with version X and higher.

**Comment by fredjean** [comment]
Java 5 reached Sun's End of Service Life on October 28th, 2009 [1](http://java.sun.com/j2se/1.5/index.jsp). I strongly recommend upgrading to Java 6.

**Comment by bjones** [comment]
Good idea, just thought it worth adding to the readme for the gem.

**Comment by fredjean** [comment]
Fair enough...

**Comment by fredjean** [comment]
I have updated my repo's copy of the read me to address this concern.
