### ISSUE TITLE
publish the new gem to rubygems

### ISSUE THREAD

**Issue by betarelease** [ikai/jruby-memcache-client#5]
The gem that is published on rubygems is 1.7.0 version which has the wrong jar dependency(java_memcached_dev). This dependency throws an ugly stack trace for lost connection.

The master has the correct dependencies "lib/java/java_memcached-release_2.5.1.jar". Also the master code does not show this stack trace(which is the expected behaviour). Can someone please push the new gem to rubygems.

Thanks

**Comment by fredjean** [comment]
Getting the gem itself back in shape for a new release. Getting the gem back in line with current practices.

**Comment by fredjean** [comment]
Pushed 1.7.1 to Rubygems. You should be able to pick up the new version.
