### ISSUE TITLE
Virson Difference

### ISSUE THREAD

**Issue by amicming** [ikai/jruby-memcache-client#6]
on github master released 1.7.1 (https://github.com/ikai/jruby-memcache-client/tree/master) 

and 

on http://rubygems.org/gems/jruby-memcache-client/versions/1.7.2

even if you click on "Homepage" from this link http://rubygems.org/gems/jruby-memcache-client/versions/1.7.2

it is displaying github virson 1.7.1

**Comment by fredjean** [comment]
The new version was committed on my personal fork and hadn't been merged into Ikai's repo. Created and merged pull request #7 to bring the change in. The repo's version is now consistent with the Rubygem's version.
